# Generated by Django 4.2.3 on 2023-08-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingbuddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
