# Generated by Django 4.2.3 on 2023-08-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingbuddy', '0002_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('value', models.IntegerField()),
                ('remainingbalance', models.IntegerField()),
            ],
        ),
    ]
