# Generated by Django 4.2.3 on 2023-08-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingbuddy', '0006_remove_log_description_remove_log_remainingbalance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
